In [7]:
import numpy as np
import pandas as pd
import math as m
import os

DATASET = 'ATLANTIC1'

In [8]:
def e_new(dis, theta2):
    val = m.e**(-dis*dis/(theta2))
    if(val < 0.5):
        return 0
    else:
        return val

In [9]:
data = np.load('./data/{}/{}.npz'.format(DATASET,DATASET))['data']
print(data.shape)

classinfo_raw = np.load('./data/{}/{}_CLASSINFO.npz'.format(DATASET,DATASET))['classinfo']
print(classinfo_raw.shape)
classinfo_max = np.max(classinfo_raw)
classinfo_min = np.min(classinfo_raw)
print(classinfo_max, classinfo_min)
classinfo = np.zeros((classinfo_max-classinfo_min+1, data.shape[1]))
print(classinfo.shape)

for i in range(data.shape[1]):
    classinfo[classinfo_raw[i]-classinfo_min,i] = 1

print(classinfo)

np.savez('./GCN_data/AGCRN/{}.npz'.format(DATASET), data=data, classinfo=classinfo)

corordinate = np.load('./data/{}/{}.npz'.format(DATASET,DATASET))['corordinate']
print(corordinate.shape)
theta2 = ((corordinate[:,0].max()-corordinate[:,0].min()))**2 + ((corordinate[:,1].max()-corordinate[:,1].min()))**2
print(theta2)

adj_mat = np.zeros((data.shape[1], data.shape[1]))
for i in range(data.shape[1]):
    for j in range(data.shape[1]):
        adj_mat[i,j] = e_new(m.sqrt((corordinate[i,0]-corordinate[j,0])**2 + (corordinate[i,1]-corordinate[j,1])**2), theta2)

t2 = np.where(adj_mat, 0, 1)
print(np.sum(t2), np.sum(adj_mat))

data_csv = pd.DataFrame(data = data)
data_csv.to_csv('./GCN_data/STGCN/{}/vel.csv'.format(DATASET.lower()), header = None, index = None)

adj_mat_csv = pd.DataFrame(data = adj_mat)
adj_mat_csv.to_csv('./GCN_data/STGCN/{}/adj_mat.csv'.format(DATASET.lower()), header = None, index = None)

class_mat_csv = pd.DataFrame(data = classinfo)
class_mat_csv.to_csv('./GCN_data/STGCN/{}/class_mat.csv'.format(DATASET.lower()), header = None, index = None)

(7305, 5238)
(5238,)
6 0
(7, 5238)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(5238, 2)
13397.0
90860 23666751.796425268


# 测试

In [10]:
DATASET = 'ATLANTIC1'

data = np.load('./GCN_data/AGCRN/{}.npz'.format(DATASET))['data']
classinfo = np.load('./GCN_data/AGCRN/{}.npz'.format(DATASET))['classinfo']

print(data.shape, classinfo.shape)
print(classinfo)
print(classinfo.min())
print(classinfo.max())

(7305, 5238) (7, 5238)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
0.0
1.0
